version: "3"

tasks:
  build:
    cmds:
      - go build -o ./bin/fontman-registry ./cmd/fontman
  lint:
    cmds:
      - echo "running linter"
  test:
    cmds:
      - go test .
  generate:
    cmds:
      - go generate ./ent
  run:
    cmds:
      - task build
      - ./bin/fontman-registry
    env:
      DATABASE_FILE: data/registry.db
