version: "3"

tasks:
  build:
    cmds:
      - go build -o ./bin/fontman-registry ./cmd/fontman
  lint:
    cmds:
      - echo "running linter"
  test:
    cmds:
      - go test .
  run:
    cmds:
      - task build
      - ./bin/fontman-registry
  migrate:
    cmds:
      - cd migrations && goose sqlite3 ../data/registry.db up
