// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"

	"github.com/gmisail/fontman/registry/ent/migrate"

	"github.com/gmisail/fontman/registry/ent/fontfamily"
	"github.com/gmisail/fontman/registry/ent/fontstyle"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// FontFamily is the client for interacting with the FontFamily builders.
	FontFamily *FontFamilyClient
	// FontStyle is the client for interacting with the FontStyle builders.
	FontStyle *FontStyleClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.FontFamily = NewFontFamilyClient(c.config)
	c.FontStyle = NewFontStyleClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		FontFamily: NewFontFamilyClient(cfg),
		FontStyle:  NewFontStyleClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		FontFamily: NewFontFamilyClient(cfg),
		FontStyle:  NewFontStyleClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		FontFamily.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.FontFamily.Use(hooks...)
	c.FontStyle.Use(hooks...)
}

// FontFamilyClient is a client for the FontFamily schema.
type FontFamilyClient struct {
	config
}

// NewFontFamilyClient returns a client for the FontFamily from the given config.
func NewFontFamilyClient(c config) *FontFamilyClient {
	return &FontFamilyClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `fontfamily.Hooks(f(g(h())))`.
func (c *FontFamilyClient) Use(hooks ...Hook) {
	c.hooks.FontFamily = append(c.hooks.FontFamily, hooks...)
}

// Create returns a builder for creating a FontFamily entity.
func (c *FontFamilyClient) Create() *FontFamilyCreate {
	mutation := newFontFamilyMutation(c.config, OpCreate)
	return &FontFamilyCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of FontFamily entities.
func (c *FontFamilyClient) CreateBulk(builders ...*FontFamilyCreate) *FontFamilyCreateBulk {
	return &FontFamilyCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for FontFamily.
func (c *FontFamilyClient) Update() *FontFamilyUpdate {
	mutation := newFontFamilyMutation(c.config, OpUpdate)
	return &FontFamilyUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FontFamilyClient) UpdateOne(ff *FontFamily) *FontFamilyUpdateOne {
	mutation := newFontFamilyMutation(c.config, OpUpdateOne, withFontFamily(ff))
	return &FontFamilyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FontFamilyClient) UpdateOneID(id int) *FontFamilyUpdateOne {
	mutation := newFontFamilyMutation(c.config, OpUpdateOne, withFontFamilyID(id))
	return &FontFamilyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for FontFamily.
func (c *FontFamilyClient) Delete() *FontFamilyDelete {
	mutation := newFontFamilyMutation(c.config, OpDelete)
	return &FontFamilyDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FontFamilyClient) DeleteOne(ff *FontFamily) *FontFamilyDeleteOne {
	return c.DeleteOneID(ff.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *FontFamilyClient) DeleteOneID(id int) *FontFamilyDeleteOne {
	builder := c.Delete().Where(fontfamily.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FontFamilyDeleteOne{builder}
}

// Query returns a query builder for FontFamily.
func (c *FontFamilyClient) Query() *FontFamilyQuery {
	return &FontFamilyQuery{
		config: c.config,
	}
}

// Get returns a FontFamily entity by its id.
func (c *FontFamilyClient) Get(ctx context.Context, id int) (*FontFamily, error) {
	return c.Query().Where(fontfamily.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FontFamilyClient) GetX(ctx context.Context, id int) *FontFamily {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *FontFamilyClient) Hooks() []Hook {
	return c.hooks.FontFamily
}

// FontStyleClient is a client for the FontStyle schema.
type FontStyleClient struct {
	config
}

// NewFontStyleClient returns a client for the FontStyle from the given config.
func NewFontStyleClient(c config) *FontStyleClient {
	return &FontStyleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `fontstyle.Hooks(f(g(h())))`.
func (c *FontStyleClient) Use(hooks ...Hook) {
	c.hooks.FontStyle = append(c.hooks.FontStyle, hooks...)
}

// Create returns a builder for creating a FontStyle entity.
func (c *FontStyleClient) Create() *FontStyleCreate {
	mutation := newFontStyleMutation(c.config, OpCreate)
	return &FontStyleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of FontStyle entities.
func (c *FontStyleClient) CreateBulk(builders ...*FontStyleCreate) *FontStyleCreateBulk {
	return &FontStyleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for FontStyle.
func (c *FontStyleClient) Update() *FontStyleUpdate {
	mutation := newFontStyleMutation(c.config, OpUpdate)
	return &FontStyleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FontStyleClient) UpdateOne(fs *FontStyle) *FontStyleUpdateOne {
	mutation := newFontStyleMutation(c.config, OpUpdateOne, withFontStyle(fs))
	return &FontStyleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FontStyleClient) UpdateOneID(id int) *FontStyleUpdateOne {
	mutation := newFontStyleMutation(c.config, OpUpdateOne, withFontStyleID(id))
	return &FontStyleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for FontStyle.
func (c *FontStyleClient) Delete() *FontStyleDelete {
	mutation := newFontStyleMutation(c.config, OpDelete)
	return &FontStyleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FontStyleClient) DeleteOne(fs *FontStyle) *FontStyleDeleteOne {
	return c.DeleteOneID(fs.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *FontStyleClient) DeleteOneID(id int) *FontStyleDeleteOne {
	builder := c.Delete().Where(fontstyle.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FontStyleDeleteOne{builder}
}

// Query returns a query builder for FontStyle.
func (c *FontStyleClient) Query() *FontStyleQuery {
	return &FontStyleQuery{
		config: c.config,
	}
}

// Get returns a FontStyle entity by its id.
func (c *FontStyleClient) Get(ctx context.Context, id int) (*FontStyle, error) {
	return c.Query().Where(fontstyle.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FontStyleClient) GetX(ctx context.Context, id int) *FontStyle {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *FontStyleClient) Hooks() []Hook {
	return c.hooks.FontStyle
}
