// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gmisail/fontman/registry/ent/fontfamily"
)

// FontFamilyCreate is the builder for creating a FontFamily entity.
type FontFamilyCreate struct {
	config
	mutation *FontFamilyMutation
	hooks    []Hook
}

// Mutation returns the FontFamilyMutation object of the builder.
func (ffc *FontFamilyCreate) Mutation() *FontFamilyMutation {
	return ffc.mutation
}

// Save creates the FontFamily in the database.
func (ffc *FontFamilyCreate) Save(ctx context.Context) (*FontFamily, error) {
	var (
		err  error
		node *FontFamily
	)
	if len(ffc.hooks) == 0 {
		if err = ffc.check(); err != nil {
			return nil, err
		}
		node, err = ffc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FontFamilyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ffc.check(); err != nil {
				return nil, err
			}
			ffc.mutation = mutation
			if node, err = ffc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ffc.hooks) - 1; i >= 0; i-- {
			if ffc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ffc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, ffc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*FontFamily)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from FontFamilyMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ffc *FontFamilyCreate) SaveX(ctx context.Context) *FontFamily {
	v, err := ffc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ffc *FontFamilyCreate) Exec(ctx context.Context) error {
	_, err := ffc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ffc *FontFamilyCreate) ExecX(ctx context.Context) {
	if err := ffc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ffc *FontFamilyCreate) check() error {
	return nil
}

func (ffc *FontFamilyCreate) sqlSave(ctx context.Context) (*FontFamily, error) {
	_node, _spec := ffc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ffc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ffc *FontFamilyCreate) createSpec() (*FontFamily, *sqlgraph.CreateSpec) {
	var (
		_node = &FontFamily{config: ffc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: fontfamily.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: fontfamily.FieldID,
			},
		}
	)
	return _node, _spec
}

// FontFamilyCreateBulk is the builder for creating many FontFamily entities in bulk.
type FontFamilyCreateBulk struct {
	config
	builders []*FontFamilyCreate
}

// Save creates the FontFamily entities in the database.
func (ffcb *FontFamilyCreateBulk) Save(ctx context.Context) ([]*FontFamily, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ffcb.builders))
	nodes := make([]*FontFamily, len(ffcb.builders))
	mutators := make([]Mutator, len(ffcb.builders))
	for i := range ffcb.builders {
		func(i int, root context.Context) {
			builder := ffcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FontFamilyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ffcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ffcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ffcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ffcb *FontFamilyCreateBulk) SaveX(ctx context.Context) []*FontFamily {
	v, err := ffcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ffcb *FontFamilyCreateBulk) Exec(ctx context.Context) error {
	_, err := ffcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ffcb *FontFamilyCreateBulk) ExecX(ctx context.Context) {
	if err := ffcb.Exec(ctx); err != nil {
		panic(err)
	}
}
