// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gmisail/fontman/registry/ent/fontstyle"
	"github.com/gmisail/fontman/registry/ent/predicate"
)

// FontStyleDelete is the builder for deleting a FontStyle entity.
type FontStyleDelete struct {
	config
	hooks    []Hook
	mutation *FontStyleMutation
}

// Where appends a list predicates to the FontStyleDelete builder.
func (fsd *FontStyleDelete) Where(ps ...predicate.FontStyle) *FontStyleDelete {
	fsd.mutation.Where(ps...)
	return fsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (fsd *FontStyleDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(fsd.hooks) == 0 {
		affected, err = fsd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FontStyleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			fsd.mutation = mutation
			affected, err = fsd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(fsd.hooks) - 1; i >= 0; i-- {
			if fsd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = fsd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, fsd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (fsd *FontStyleDelete) ExecX(ctx context.Context) int {
	n, err := fsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (fsd *FontStyleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: fontstyle.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: fontstyle.FieldID,
			},
		},
	}
	if ps := fsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, fsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// FontStyleDeleteOne is the builder for deleting a single FontStyle entity.
type FontStyleDeleteOne struct {
	fsd *FontStyleDelete
}

// Exec executes the deletion query.
func (fsdo *FontStyleDeleteOne) Exec(ctx context.Context) error {
	n, err := fsdo.fsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{fontstyle.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (fsdo *FontStyleDeleteOne) ExecX(ctx context.Context) {
	fsdo.fsd.ExecX(ctx)
}
