// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gmisail/fontman/registry/ent/fontfamily"
	"github.com/gmisail/fontman/registry/ent/predicate"
)

// FontFamilyDelete is the builder for deleting a FontFamily entity.
type FontFamilyDelete struct {
	config
	hooks    []Hook
	mutation *FontFamilyMutation
}

// Where appends a list predicates to the FontFamilyDelete builder.
func (ffd *FontFamilyDelete) Where(ps ...predicate.FontFamily) *FontFamilyDelete {
	ffd.mutation.Where(ps...)
	return ffd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ffd *FontFamilyDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ffd.hooks) == 0 {
		affected, err = ffd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FontFamilyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ffd.mutation = mutation
			affected, err = ffd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ffd.hooks) - 1; i >= 0; i-- {
			if ffd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ffd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ffd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ffd *FontFamilyDelete) ExecX(ctx context.Context) int {
	n, err := ffd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ffd *FontFamilyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: fontfamily.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: fontfamily.FieldID,
			},
		},
	}
	if ps := ffd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ffd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// FontFamilyDeleteOne is the builder for deleting a single FontFamily entity.
type FontFamilyDeleteOne struct {
	ffd *FontFamilyDelete
}

// Exec executes the deletion query.
func (ffdo *FontFamilyDeleteOne) Exec(ctx context.Context) error {
	n, err := ffdo.ffd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{fontfamily.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ffdo *FontFamilyDeleteOne) ExecX(ctx context.Context) {
	ffdo.ffd.ExecX(ctx)
}
