// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gmisail/fontman/registry/ent/fontstyle"
	"github.com/gmisail/fontman/registry/ent/predicate"
)

// FontStyleQuery is the builder for querying FontStyle entities.
type FontStyleQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.FontStyle
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FontStyleQuery builder.
func (fsq *FontStyleQuery) Where(ps ...predicate.FontStyle) *FontStyleQuery {
	fsq.predicates = append(fsq.predicates, ps...)
	return fsq
}

// Limit adds a limit step to the query.
func (fsq *FontStyleQuery) Limit(limit int) *FontStyleQuery {
	fsq.limit = &limit
	return fsq
}

// Offset adds an offset step to the query.
func (fsq *FontStyleQuery) Offset(offset int) *FontStyleQuery {
	fsq.offset = &offset
	return fsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fsq *FontStyleQuery) Unique(unique bool) *FontStyleQuery {
	fsq.unique = &unique
	return fsq
}

// Order adds an order step to the query.
func (fsq *FontStyleQuery) Order(o ...OrderFunc) *FontStyleQuery {
	fsq.order = append(fsq.order, o...)
	return fsq
}

// First returns the first FontStyle entity from the query.
// Returns a *NotFoundError when no FontStyle was found.
func (fsq *FontStyleQuery) First(ctx context.Context) (*FontStyle, error) {
	nodes, err := fsq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{fontstyle.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fsq *FontStyleQuery) FirstX(ctx context.Context) *FontStyle {
	node, err := fsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FontStyle ID from the query.
// Returns a *NotFoundError when no FontStyle ID was found.
func (fsq *FontStyleQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fsq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{fontstyle.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fsq *FontStyleQuery) FirstIDX(ctx context.Context) int {
	id, err := fsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FontStyle entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FontStyle entity is found.
// Returns a *NotFoundError when no FontStyle entities are found.
func (fsq *FontStyleQuery) Only(ctx context.Context) (*FontStyle, error) {
	nodes, err := fsq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{fontstyle.Label}
	default:
		return nil, &NotSingularError{fontstyle.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fsq *FontStyleQuery) OnlyX(ctx context.Context) *FontStyle {
	node, err := fsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FontStyle ID in the query.
// Returns a *NotSingularError when more than one FontStyle ID is found.
// Returns a *NotFoundError when no entities are found.
func (fsq *FontStyleQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fsq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{fontstyle.Label}
	default:
		err = &NotSingularError{fontstyle.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fsq *FontStyleQuery) OnlyIDX(ctx context.Context) int {
	id, err := fsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FontStyles.
func (fsq *FontStyleQuery) All(ctx context.Context) ([]*FontStyle, error) {
	if err := fsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return fsq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (fsq *FontStyleQuery) AllX(ctx context.Context) []*FontStyle {
	nodes, err := fsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FontStyle IDs.
func (fsq *FontStyleQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := fsq.Select(fontstyle.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fsq *FontStyleQuery) IDsX(ctx context.Context) []int {
	ids, err := fsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fsq *FontStyleQuery) Count(ctx context.Context) (int, error) {
	if err := fsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return fsq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (fsq *FontStyleQuery) CountX(ctx context.Context) int {
	count, err := fsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fsq *FontStyleQuery) Exist(ctx context.Context) (bool, error) {
	if err := fsq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return fsq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (fsq *FontStyleQuery) ExistX(ctx context.Context) bool {
	exist, err := fsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FontStyleQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fsq *FontStyleQuery) Clone() *FontStyleQuery {
	if fsq == nil {
		return nil
	}
	return &FontStyleQuery{
		config:     fsq.config,
		limit:      fsq.limit,
		offset:     fsq.offset,
		order:      append([]OrderFunc{}, fsq.order...),
		predicates: append([]predicate.FontStyle{}, fsq.predicates...),
		// clone intermediate query.
		sql:    fsq.sql.Clone(),
		path:   fsq.path,
		unique: fsq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (fsq *FontStyleQuery) GroupBy(field string, fields ...string) *FontStyleGroupBy {
	grbuild := &FontStyleGroupBy{config: fsq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := fsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return fsq.sqlQuery(ctx), nil
	}
	grbuild.label = fontstyle.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (fsq *FontStyleQuery) Select(fields ...string) *FontStyleSelect {
	fsq.fields = append(fsq.fields, fields...)
	selbuild := &FontStyleSelect{FontStyleQuery: fsq}
	selbuild.label = fontstyle.Label
	selbuild.flds, selbuild.scan = &fsq.fields, selbuild.Scan
	return selbuild
}

func (fsq *FontStyleQuery) prepareQuery(ctx context.Context) error {
	for _, f := range fsq.fields {
		if !fontstyle.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if fsq.path != nil {
		prev, err := fsq.path(ctx)
		if err != nil {
			return err
		}
		fsq.sql = prev
	}
	return nil
}

func (fsq *FontStyleQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FontStyle, error) {
	var (
		nodes = []*FontStyle{}
		_spec = fsq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*FontStyle).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &FontStyle{config: fsq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, fsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (fsq *FontStyleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fsq.querySpec()
	_spec.Node.Columns = fsq.fields
	if len(fsq.fields) > 0 {
		_spec.Unique = fsq.unique != nil && *fsq.unique
	}
	return sqlgraph.CountNodes(ctx, fsq.driver, _spec)
}

func (fsq *FontStyleQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := fsq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (fsq *FontStyleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   fontstyle.Table,
			Columns: fontstyle.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: fontstyle.FieldID,
			},
		},
		From:   fsq.sql,
		Unique: true,
	}
	if unique := fsq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := fsq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fontstyle.FieldID)
		for i := range fields {
			if fields[i] != fontstyle.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := fsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fsq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fsq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fsq *FontStyleQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fsq.driver.Dialect())
	t1 := builder.Table(fontstyle.Table)
	columns := fsq.fields
	if len(columns) == 0 {
		columns = fontstyle.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fsq.sql != nil {
		selector = fsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fsq.unique != nil && *fsq.unique {
		selector.Distinct()
	}
	for _, p := range fsq.predicates {
		p(selector)
	}
	for _, p := range fsq.order {
		p(selector)
	}
	if offset := fsq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fsq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FontStyleGroupBy is the group-by builder for FontStyle entities.
type FontStyleGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fsgb *FontStyleGroupBy) Aggregate(fns ...AggregateFunc) *FontStyleGroupBy {
	fsgb.fns = append(fsgb.fns, fns...)
	return fsgb
}

// Scan applies the group-by query and scans the result into the given value.
func (fsgb *FontStyleGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := fsgb.path(ctx)
	if err != nil {
		return err
	}
	fsgb.sql = query
	return fsgb.sqlScan(ctx, v)
}

func (fsgb *FontStyleGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range fsgb.fields {
		if !fontstyle.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := fsgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fsgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (fsgb *FontStyleGroupBy) sqlQuery() *sql.Selector {
	selector := fsgb.sql.Select()
	aggregation := make([]string, 0, len(fsgb.fns))
	for _, fn := range fsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(fsgb.fields)+len(fsgb.fns))
		for _, f := range fsgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(fsgb.fields...)...)
}

// FontStyleSelect is the builder for selecting fields of FontStyle entities.
type FontStyleSelect struct {
	*FontStyleQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (fss *FontStyleSelect) Scan(ctx context.Context, v interface{}) error {
	if err := fss.prepareQuery(ctx); err != nil {
		return err
	}
	fss.sql = fss.FontStyleQuery.sqlQuery(ctx)
	return fss.sqlScan(ctx, v)
}

func (fss *FontStyleSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := fss.sql.Query()
	if err := fss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
