// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gmisail/fontman/registry/ent/fontfamily"
	"github.com/gmisail/fontman/registry/ent/predicate"
)

// FontFamilyUpdate is the builder for updating FontFamily entities.
type FontFamilyUpdate struct {
	config
	hooks    []Hook
	mutation *FontFamilyMutation
}

// Where appends a list predicates to the FontFamilyUpdate builder.
func (ffu *FontFamilyUpdate) Where(ps ...predicate.FontFamily) *FontFamilyUpdate {
	ffu.mutation.Where(ps...)
	return ffu
}

// Mutation returns the FontFamilyMutation object of the builder.
func (ffu *FontFamilyUpdate) Mutation() *FontFamilyMutation {
	return ffu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ffu *FontFamilyUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ffu.hooks) == 0 {
		affected, err = ffu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FontFamilyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ffu.mutation = mutation
			affected, err = ffu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ffu.hooks) - 1; i >= 0; i-- {
			if ffu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ffu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ffu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ffu *FontFamilyUpdate) SaveX(ctx context.Context) int {
	affected, err := ffu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ffu *FontFamilyUpdate) Exec(ctx context.Context) error {
	_, err := ffu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ffu *FontFamilyUpdate) ExecX(ctx context.Context) {
	if err := ffu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ffu *FontFamilyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   fontfamily.Table,
			Columns: fontfamily.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: fontfamily.FieldID,
			},
		},
	}
	if ps := ffu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ffu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fontfamily.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// FontFamilyUpdateOne is the builder for updating a single FontFamily entity.
type FontFamilyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FontFamilyMutation
}

// Mutation returns the FontFamilyMutation object of the builder.
func (ffuo *FontFamilyUpdateOne) Mutation() *FontFamilyMutation {
	return ffuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ffuo *FontFamilyUpdateOne) Select(field string, fields ...string) *FontFamilyUpdateOne {
	ffuo.fields = append([]string{field}, fields...)
	return ffuo
}

// Save executes the query and returns the updated FontFamily entity.
func (ffuo *FontFamilyUpdateOne) Save(ctx context.Context) (*FontFamily, error) {
	var (
		err  error
		node *FontFamily
	)
	if len(ffuo.hooks) == 0 {
		node, err = ffuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FontFamilyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ffuo.mutation = mutation
			node, err = ffuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ffuo.hooks) - 1; i >= 0; i-- {
			if ffuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ffuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, ffuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*FontFamily)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from FontFamilyMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ffuo *FontFamilyUpdateOne) SaveX(ctx context.Context) *FontFamily {
	node, err := ffuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ffuo *FontFamilyUpdateOne) Exec(ctx context.Context) error {
	_, err := ffuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ffuo *FontFamilyUpdateOne) ExecX(ctx context.Context) {
	if err := ffuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ffuo *FontFamilyUpdateOne) sqlSave(ctx context.Context) (_node *FontFamily, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   fontfamily.Table,
			Columns: fontfamily.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: fontfamily.FieldID,
			},
		},
	}
	id, ok := ffuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FontFamily.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ffuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fontfamily.FieldID)
		for _, f := range fields {
			if !fontfamily.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != fontfamily.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ffuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &FontFamily{config: ffuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ffuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fontfamily.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
