// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gmisail/fontman/registry/ent/fontstyle"
)

// FontStyleCreate is the builder for creating a FontStyle entity.
type FontStyleCreate struct {
	config
	mutation *FontStyleMutation
	hooks    []Hook
}

// Mutation returns the FontStyleMutation object of the builder.
func (fsc *FontStyleCreate) Mutation() *FontStyleMutation {
	return fsc.mutation
}

// Save creates the FontStyle in the database.
func (fsc *FontStyleCreate) Save(ctx context.Context) (*FontStyle, error) {
	var (
		err  error
		node *FontStyle
	)
	if len(fsc.hooks) == 0 {
		if err = fsc.check(); err != nil {
			return nil, err
		}
		node, err = fsc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FontStyleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = fsc.check(); err != nil {
				return nil, err
			}
			fsc.mutation = mutation
			if node, err = fsc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(fsc.hooks) - 1; i >= 0; i-- {
			if fsc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = fsc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, fsc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*FontStyle)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from FontStyleMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (fsc *FontStyleCreate) SaveX(ctx context.Context) *FontStyle {
	v, err := fsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fsc *FontStyleCreate) Exec(ctx context.Context) error {
	_, err := fsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fsc *FontStyleCreate) ExecX(ctx context.Context) {
	if err := fsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fsc *FontStyleCreate) check() error {
	return nil
}

func (fsc *FontStyleCreate) sqlSave(ctx context.Context) (*FontStyle, error) {
	_node, _spec := fsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, fsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (fsc *FontStyleCreate) createSpec() (*FontStyle, *sqlgraph.CreateSpec) {
	var (
		_node = &FontStyle{config: fsc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: fontstyle.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: fontstyle.FieldID,
			},
		}
	)
	return _node, _spec
}

// FontStyleCreateBulk is the builder for creating many FontStyle entities in bulk.
type FontStyleCreateBulk struct {
	config
	builders []*FontStyleCreate
}

// Save creates the FontStyle entities in the database.
func (fscb *FontStyleCreateBulk) Save(ctx context.Context) ([]*FontStyle, error) {
	specs := make([]*sqlgraph.CreateSpec, len(fscb.builders))
	nodes := make([]*FontStyle, len(fscb.builders))
	mutators := make([]Mutator, len(fscb.builders))
	for i := range fscb.builders {
		func(i int, root context.Context) {
			builder := fscb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FontStyleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, fscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, fscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, fscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (fscb *FontStyleCreateBulk) SaveX(ctx context.Context) []*FontStyle {
	v, err := fscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fscb *FontStyleCreateBulk) Exec(ctx context.Context) error {
	_, err := fscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fscb *FontStyleCreateBulk) ExecX(ctx context.Context) {
	if err := fscb.Exec(ctx); err != nil {
		panic(err)
	}
}
