// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gmisail/fontman/registry/ent/fontstyle"
	"github.com/gmisail/fontman/registry/ent/predicate"
)

// FontStyleUpdate is the builder for updating FontStyle entities.
type FontStyleUpdate struct {
	config
	hooks    []Hook
	mutation *FontStyleMutation
}

// Where appends a list predicates to the FontStyleUpdate builder.
func (fsu *FontStyleUpdate) Where(ps ...predicate.FontStyle) *FontStyleUpdate {
	fsu.mutation.Where(ps...)
	return fsu
}

// Mutation returns the FontStyleMutation object of the builder.
func (fsu *FontStyleUpdate) Mutation() *FontStyleMutation {
	return fsu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (fsu *FontStyleUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(fsu.hooks) == 0 {
		affected, err = fsu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FontStyleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			fsu.mutation = mutation
			affected, err = fsu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(fsu.hooks) - 1; i >= 0; i-- {
			if fsu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = fsu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, fsu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (fsu *FontStyleUpdate) SaveX(ctx context.Context) int {
	affected, err := fsu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (fsu *FontStyleUpdate) Exec(ctx context.Context) error {
	_, err := fsu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fsu *FontStyleUpdate) ExecX(ctx context.Context) {
	if err := fsu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (fsu *FontStyleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   fontstyle.Table,
			Columns: fontstyle.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: fontstyle.FieldID,
			},
		},
	}
	if ps := fsu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, fsu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fontstyle.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// FontStyleUpdateOne is the builder for updating a single FontStyle entity.
type FontStyleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FontStyleMutation
}

// Mutation returns the FontStyleMutation object of the builder.
func (fsuo *FontStyleUpdateOne) Mutation() *FontStyleMutation {
	return fsuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (fsuo *FontStyleUpdateOne) Select(field string, fields ...string) *FontStyleUpdateOne {
	fsuo.fields = append([]string{field}, fields...)
	return fsuo
}

// Save executes the query and returns the updated FontStyle entity.
func (fsuo *FontStyleUpdateOne) Save(ctx context.Context) (*FontStyle, error) {
	var (
		err  error
		node *FontStyle
	)
	if len(fsuo.hooks) == 0 {
		node, err = fsuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FontStyleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			fsuo.mutation = mutation
			node, err = fsuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(fsuo.hooks) - 1; i >= 0; i-- {
			if fsuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = fsuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, fsuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*FontStyle)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from FontStyleMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (fsuo *FontStyleUpdateOne) SaveX(ctx context.Context) *FontStyle {
	node, err := fsuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (fsuo *FontStyleUpdateOne) Exec(ctx context.Context) error {
	_, err := fsuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fsuo *FontStyleUpdateOne) ExecX(ctx context.Context) {
	if err := fsuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (fsuo *FontStyleUpdateOne) sqlSave(ctx context.Context) (_node *FontStyle, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   fontstyle.Table,
			Columns: fontstyle.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: fontstyle.FieldID,
			},
		},
	}
	id, ok := fsuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FontStyle.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := fsuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fontstyle.FieldID)
		for _, f := range fields {
			if !fontstyle.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != fontstyle.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := fsuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &FontStyle{config: fsuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, fsuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fontstyle.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
