// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gmisail/fontman/registry/ent/fontfamily"
	"github.com/gmisail/fontman/registry/ent/predicate"
)

// FontFamilyQuery is the builder for querying FontFamily entities.
type FontFamilyQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.FontFamily
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FontFamilyQuery builder.
func (ffq *FontFamilyQuery) Where(ps ...predicate.FontFamily) *FontFamilyQuery {
	ffq.predicates = append(ffq.predicates, ps...)
	return ffq
}

// Limit adds a limit step to the query.
func (ffq *FontFamilyQuery) Limit(limit int) *FontFamilyQuery {
	ffq.limit = &limit
	return ffq
}

// Offset adds an offset step to the query.
func (ffq *FontFamilyQuery) Offset(offset int) *FontFamilyQuery {
	ffq.offset = &offset
	return ffq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ffq *FontFamilyQuery) Unique(unique bool) *FontFamilyQuery {
	ffq.unique = &unique
	return ffq
}

// Order adds an order step to the query.
func (ffq *FontFamilyQuery) Order(o ...OrderFunc) *FontFamilyQuery {
	ffq.order = append(ffq.order, o...)
	return ffq
}

// First returns the first FontFamily entity from the query.
// Returns a *NotFoundError when no FontFamily was found.
func (ffq *FontFamilyQuery) First(ctx context.Context) (*FontFamily, error) {
	nodes, err := ffq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{fontfamily.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ffq *FontFamilyQuery) FirstX(ctx context.Context) *FontFamily {
	node, err := ffq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FontFamily ID from the query.
// Returns a *NotFoundError when no FontFamily ID was found.
func (ffq *FontFamilyQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ffq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{fontfamily.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ffq *FontFamilyQuery) FirstIDX(ctx context.Context) int {
	id, err := ffq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FontFamily entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FontFamily entity is found.
// Returns a *NotFoundError when no FontFamily entities are found.
func (ffq *FontFamilyQuery) Only(ctx context.Context) (*FontFamily, error) {
	nodes, err := ffq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{fontfamily.Label}
	default:
		return nil, &NotSingularError{fontfamily.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ffq *FontFamilyQuery) OnlyX(ctx context.Context) *FontFamily {
	node, err := ffq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FontFamily ID in the query.
// Returns a *NotSingularError when more than one FontFamily ID is found.
// Returns a *NotFoundError when no entities are found.
func (ffq *FontFamilyQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ffq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{fontfamily.Label}
	default:
		err = &NotSingularError{fontfamily.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ffq *FontFamilyQuery) OnlyIDX(ctx context.Context) int {
	id, err := ffq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FontFamilies.
func (ffq *FontFamilyQuery) All(ctx context.Context) ([]*FontFamily, error) {
	if err := ffq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ffq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ffq *FontFamilyQuery) AllX(ctx context.Context) []*FontFamily {
	nodes, err := ffq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FontFamily IDs.
func (ffq *FontFamilyQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := ffq.Select(fontfamily.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ffq *FontFamilyQuery) IDsX(ctx context.Context) []int {
	ids, err := ffq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ffq *FontFamilyQuery) Count(ctx context.Context) (int, error) {
	if err := ffq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ffq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ffq *FontFamilyQuery) CountX(ctx context.Context) int {
	count, err := ffq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ffq *FontFamilyQuery) Exist(ctx context.Context) (bool, error) {
	if err := ffq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ffq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ffq *FontFamilyQuery) ExistX(ctx context.Context) bool {
	exist, err := ffq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FontFamilyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ffq *FontFamilyQuery) Clone() *FontFamilyQuery {
	if ffq == nil {
		return nil
	}
	return &FontFamilyQuery{
		config:     ffq.config,
		limit:      ffq.limit,
		offset:     ffq.offset,
		order:      append([]OrderFunc{}, ffq.order...),
		predicates: append([]predicate.FontFamily{}, ffq.predicates...),
		// clone intermediate query.
		sql:    ffq.sql.Clone(),
		path:   ffq.path,
		unique: ffq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (ffq *FontFamilyQuery) GroupBy(field string, fields ...string) *FontFamilyGroupBy {
	grbuild := &FontFamilyGroupBy{config: ffq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ffq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ffq.sqlQuery(ctx), nil
	}
	grbuild.label = fontfamily.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (ffq *FontFamilyQuery) Select(fields ...string) *FontFamilySelect {
	ffq.fields = append(ffq.fields, fields...)
	selbuild := &FontFamilySelect{FontFamilyQuery: ffq}
	selbuild.label = fontfamily.Label
	selbuild.flds, selbuild.scan = &ffq.fields, selbuild.Scan
	return selbuild
}

func (ffq *FontFamilyQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ffq.fields {
		if !fontfamily.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ffq.path != nil {
		prev, err := ffq.path(ctx)
		if err != nil {
			return err
		}
		ffq.sql = prev
	}
	return nil
}

func (ffq *FontFamilyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FontFamily, error) {
	var (
		nodes = []*FontFamily{}
		_spec = ffq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*FontFamily).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &FontFamily{config: ffq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ffq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ffq *FontFamilyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ffq.querySpec()
	_spec.Node.Columns = ffq.fields
	if len(ffq.fields) > 0 {
		_spec.Unique = ffq.unique != nil && *ffq.unique
	}
	return sqlgraph.CountNodes(ctx, ffq.driver, _spec)
}

func (ffq *FontFamilyQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ffq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (ffq *FontFamilyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   fontfamily.Table,
			Columns: fontfamily.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: fontfamily.FieldID,
			},
		},
		From:   ffq.sql,
		Unique: true,
	}
	if unique := ffq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ffq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fontfamily.FieldID)
		for i := range fields {
			if fields[i] != fontfamily.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ffq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ffq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ffq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ffq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ffq *FontFamilyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ffq.driver.Dialect())
	t1 := builder.Table(fontfamily.Table)
	columns := ffq.fields
	if len(columns) == 0 {
		columns = fontfamily.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ffq.sql != nil {
		selector = ffq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ffq.unique != nil && *ffq.unique {
		selector.Distinct()
	}
	for _, p := range ffq.predicates {
		p(selector)
	}
	for _, p := range ffq.order {
		p(selector)
	}
	if offset := ffq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ffq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FontFamilyGroupBy is the group-by builder for FontFamily entities.
type FontFamilyGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ffgb *FontFamilyGroupBy) Aggregate(fns ...AggregateFunc) *FontFamilyGroupBy {
	ffgb.fns = append(ffgb.fns, fns...)
	return ffgb
}

// Scan applies the group-by query and scans the result into the given value.
func (ffgb *FontFamilyGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := ffgb.path(ctx)
	if err != nil {
		return err
	}
	ffgb.sql = query
	return ffgb.sqlScan(ctx, v)
}

func (ffgb *FontFamilyGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range ffgb.fields {
		if !fontfamily.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ffgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ffgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ffgb *FontFamilyGroupBy) sqlQuery() *sql.Selector {
	selector := ffgb.sql.Select()
	aggregation := make([]string, 0, len(ffgb.fns))
	for _, fn := range ffgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(ffgb.fields)+len(ffgb.fns))
		for _, f := range ffgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(ffgb.fields...)...)
}

// FontFamilySelect is the builder for selecting fields of FontFamily entities.
type FontFamilySelect struct {
	*FontFamilyQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ffs *FontFamilySelect) Scan(ctx context.Context, v interface{}) error {
	if err := ffs.prepareQuery(ctx); err != nil {
		return err
	}
	ffs.sql = ffs.FontFamilyQuery.sqlQuery(ctx)
	return ffs.sqlScan(ctx, v)
}

func (ffs *FontFamilySelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ffs.sql.Query()
	if err := ffs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
