// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/gmisail/fontman/registry/ent/fontfamily"
)

// FontFamily is the model entity for the FontFamily schema.
type FontFamily struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FontFamily) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case fontfamily.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type FontFamily", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FontFamily fields.
func (ff *FontFamily) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case fontfamily.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ff.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this FontFamily.
// Note that you need to call FontFamily.Unwrap() before calling this method if this FontFamily
// was returned from a transaction, and the transaction was committed or rolled back.
func (ff *FontFamily) Update() *FontFamilyUpdateOne {
	return (&FontFamilyClient{config: ff.config}).UpdateOne(ff)
}

// Unwrap unwraps the FontFamily entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ff *FontFamily) Unwrap() *FontFamily {
	_tx, ok := ff.config.driver.(*txDriver)
	if !ok {
		panic("ent: FontFamily is not a transactional entity")
	}
	ff.config.driver = _tx.drv
	return ff
}

// String implements the fmt.Stringer.
func (ff *FontFamily) String() string {
	var builder strings.Builder
	builder.WriteString("FontFamily(")
	builder.WriteString(fmt.Sprintf("id=%v", ff.ID))
	builder.WriteByte(')')
	return builder.String()
}

// FontFamilies is a parsable slice of FontFamily.
type FontFamilies []*FontFamily

func (ff FontFamilies) config(cfg config) {
	for _i := range ff {
		ff[_i].config = cfg
	}
}
