// Code generated by ent, DO NOT EDIT.

package fontstyle

const (
	// Label holds the string label denoting the fontstyle type in the database.
	Label = "font_style"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the fontstyle in the database.
	Table = "font_styles"
)

// Columns holds all SQL columns for fontstyle fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
