// Code generated by ent, DO NOT EDIT.

package fontfamily

const (
	// Label holds the string label denoting the fontfamily type in the database.
	Label = "font_family"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the fontfamily in the database.
	Table = "font_families"
)

// Columns holds all SQL columns for fontfamily fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
