// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// FontFamily is the predicate function for fontfamily builders.
type FontFamily func(*sql.Selector)

// FontStyle is the predicate function for fontstyle builders.
type FontStyle func(*sql.Selector)
